# Generated by Django 3.2 on 2023-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='delete_notes',
            name='line',
            field=models.CharField(default='linea elimindada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delete_notes',
            name='note',
            field=models.CharField(default='linea eliminada', max_length=255),
            preserve_default=False,
        ),
    ]
