# Generated by Django 3.2 on 2023-03-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iduser',
            field=models.IntegerField(default=0),
        ),
    ]
