# Generated by Django 3.2 on 2023-09-11 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLines', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='config_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='device_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.IntegerField()),
                ('point', models.CharField(max_length=200)),
                ('lineid', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('shift', models.CharField(max_length=200)),
                ('starTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.IntegerField()),
                ('line', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('dataType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountDevice', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='lines_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.IntegerField()),
                ('point', models.CharField(max_length=200)),
                ('lineid', models.IntegerField(default=0)),
                ('shift', models.CharField(max_length=200)),
                ('totalTime', models.FloatField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='total_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.IntegerField(null=True)),
                ('point', models.CharField(max_length=255, null=True)),
                ('lineid', models.IntegerField(null=True)),
                ('shift', models.CharField(max_length=255, null=True)),
                ('totalTime', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='line_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineName', models.CharField(max_length=200)),
                ('amountDevices', models.IntegerField(default=0)),
                ('shift', models.CharField(max_length=200)),
                ('starTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(default='activo', max_length=255)),
                ('notes', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='device_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=200)),
                ('data', models.BigIntegerField()),
                ('lineid', models.IntegerField(default=0)),
                ('status', models.CharField(default='activo', max_length=255)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineManagement.devices')),
            ],
        ),
        migrations.CreateModel(
            name='device_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('shift', models.CharField(max_length=200)),
                ('lineid', models.IntegerField(default=0)),
                ('production_data', models.IntegerField()),
                ('created_at', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('battery_percentage', models.FloatField(blank=True, null=True)),
                ('deviceId_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lineManagement.devices')),
            ],
        ),
    ]
