# Generated by Django 3.2 on 2023-09-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='deviceId',
        ),
    ]
