# Generated by Django 3.2 on 2023-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0002_remove_devices_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_maintenance',
            name='maintenanceSupervisor',
            field=models.CharField(default='Mariano Jerez ', max_length=200, null=True),
        ),
    ]
