# Generated by Django 3.2 on 2023-10-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0003_device_maintenance_maintenancesupervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_maintenance',
            name='productionsupervisor',
            field=models.CharField(default='Frank Bosch ', max_length=200, null=True),
        ),
    ]
