# Generated by Django 3.2 on 2023-10-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0004_device_maintenance_productionsupervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='optimal_production_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('optimal_production', models.IntegerField(default=0)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineManagement.devices')),
            ],
        ),
    ]
