# Generated by Django 3.2 on 2023-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0005_optimal_production_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_maintenance',
            name='maintenanceSupervisor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device_maintenance',
            name='productionsupervisor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
