# Generated by Django 3.2 on 2023-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0007_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.CharField(default='no se ha proporcionado un mail', max_length=255),
        ),
    ]
