# Generated by Django 3.2 on 2023-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0008_supervisor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='status',
            field=models.CharField(default='activo', max_length=200),
        ),
    ]
