# Generated by Django 3.2 on 2023-03-05 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0002_auto_20230305_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_maintance',
            name='starTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='device_status',
            name='starTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='line_status',
            name='starTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lines_maintance',
            name='starTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
