# Generated by Django 3.2 on 2023-03-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0003_auto_20230305_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_maintance',
            name='endTime',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='device_status',
            name='endTime',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='line_status',
            name='endTime',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='lines_maintance',
            name='endTime',
            field=models.DateTimeField(default=0),
        ),
    ]
