# Generated by Django 3.2 on 2023-03-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0006_auto_20230307_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountDevice', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('dataType', models.CharField(max_length=200)),
            ],
        ),
    ]
