# Generated by Django 3.2 on 2023-03-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0007_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_status',
            name='status',
            field=models.CharField(default='activo', max_length=255),
        ),
    ]
