# Generated by Django 3.2 on 2023-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0008_alter_line_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_status',
            name='endTime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
