# Generated by Django 3.2 on 2023-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0009_alter_line_status_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_status',
            name='timeMaintance',
            field=models.TimeField(default=None, null=True),
        ),
    ]
