# Generated by Django 3.2 on 2023-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0010_alter_line_status_timemaintance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_maintance',
            old_name='deviceID',
            new_name='deviceId',
        ),
        migrations.AlterField(
            model_name='device_status',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lines_maintance',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
