# Generated by Django 3.2 on 2023-03-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0010_alter_line_status_timemaintance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_maintance',
            old_name='deviceID',
            new_name='deviceId',
        ),
    ]
