# Generated by Django 3.2 on 2023-03-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0011_auto_20230321_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_maintance',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
