# Generated by Django 3.2 on 2023-03-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0012_alter_device_maintance_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_status',
            name='status',
            field=models.CharField(default='activo', max_length=255),
        ),
    ]
