# Generated by Django 3.2 on 2023-04-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0013_alter_device_status_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=200)),
                ('production_data', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineManagement.devices')),
            ],
        ),
    ]
