# Generated by Django 3.2 on 2023-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0014_device_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_production',
            name='lineid',
            field=models.IntegerField(default=0),
        ),
    ]
