# Generated by Django 3.2 on 2023-04-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0016_alter_device_production_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_production',
            name='created_at',
            field=models.CharField(max_length=15000),
        ),
    ]
