# Generated by Django 3.2 on 2023-04-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0017_alter_device_production_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_production',
            name='created_at',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='device_production',
            name='production_data',
            field=models.TextField(),
        ),
    ]
