# Generated by Django 3.2 on 2023-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lineManagement", "0018_auto_20230414_1952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device_production",
            name="created_at",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="device_production",
            name="production_data",
            field=models.CharField(max_length=250),
        ),
    ]
