# Generated by Django 3.2 on 2023-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0019_auto_20230416_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_production',
            name='created_at',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='device_production',
            name='production_data',
            field=models.CharField(max_length=250),
        ),
    ]
