# Generated by Django 3.2 on 2023-04-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0020_auto_20230416_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_production',
            name='production_data',
            field=models.IntegerField(max_length=250),
        ),
    ]
