# Generated by Django 3.2 on 2023-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0021_alter_device_production_production_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_production',
            name='production_data',
            field=models.IntegerField(),
        ),
    ]
