# Generated by Django 3.2 on 2023-04-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0022_alter_device_production_production_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=200)),
                ('lineid', models.IntegerField(default=0)),
                ('production_data', models.IntegerField()),
                ('created_at', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineManagement.devices')),
            ],
        ),
    ]
