# Generated by Django 3.2 on 2023-05-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0019_auto_20230417_1703'),
        ('lineManagement', '0023_graphs'),
    ]

    operations = [
    ]
