# Generated by Django 3.2 on 2023-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0025_auto_20230504_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='production_data',
            new_name='potential_production',
        ),
        migrations.RemoveField(
            model_name='graphs',
            name='created_at',
        ),
        migrations.AddField(
            model_name='graphs',
            name='total_production',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
