# Generated by Django 3.2 on 2023-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0027_auto_20230515_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.IntegerField()),
                ('point', models.CharField(max_length=200)),
                ('lineid', models.IntegerField(default=0)),
                ('shift', models.CharField(max_length=200)),
                ('totalTime', models.DurationField()),
            ],
        ),
    ]
