# Generated by Django 3.2 on 2023-05-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0029_total_maintenance_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='total_maintenance',
        ),
    ]
