# Generated by Django 3.2 on 2023-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0031_total_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_maintenance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
