# Generated by Django 3.2 on 2023-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0032_alter_total_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_maintenance',
            name='totalTime',
            field=models.FloatField(),
        ),
    ]
