# Generated by Django 3.2 on 2023-05-21 01:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_iduser'),
        ('lineManagement', '0033_alter_total_maintenance_totaltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='pepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineName', models.CharField(max_length=200)),
                ('amountDevices', models.IntegerField(default=0)),
                ('shift', models.CharField(max_length=200)),
                ('starTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(default='activo', max_length=255)),
                ('notes', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
