# Generated by Django 3.2 on 2023-05-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineManagement', '0034_pepe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pepe',
        ),
    ]
